In [41]:
from sklearn import ensemble
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree

import pandas as pd
import pandas_profiling
import pixiedust
import pivottablejs
import seaborn

In [2]:
df = pd.read_csv("titanic.csv")

In [3]:
df

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3.0,Master. Thomas Henry Sage,male,5.0,8,2,69.5500
1,0,3.0,Miss. Constance Gladys Sage,female,8.0,8,2,69.5500
2,0,3.0,Mr. Frederick Sage,male,17.0,8,2,69.5500
3,0,3.0,Mr. George John Jr Sage,male,20.0,8,2,69.5500
4,0,3.0,Miss. Stella Anna Sage,female,21.0,8,2,69.5500
5,0,3.0,Mr. Douglas Bullen Sage,male,18.0,8,2,69.5500
6,0,3.0,Miss. Dorothy Edith Sage,female,14.0,8,2,69.5500
7,0,3.0,Master. William Frederick Goodwin,male,11.0,5,2,46.9000
8,0,3.0,Miss. Lillian Amy Goodwin,female,16.0,5,2,46.9000
9,0,3.0,Master. Sidney Leonard Goodwin,male,1.0,5,2,46.9000
10,0,3.0,Master. Harold Victor Goodwin,male,9.0,5,2,46.9000
11,0,3.0,Mr. Charles Edward Goodwin,male,14.0,5,2,46.9000
12,0,3.0,Master. Eugene Rice,male,2.0,4,1,29.1250
13,0,3.0,Master. Juha Niilo Panula,male,7.0,4,1,39.6875
14,1,3.0,Miss. Erna Alexandra Andersson,female,17.0,4,2,7.9250
15,0,3.0,Miss. Ellis Anna Maria Andersson,female,2.0,4,2,31.2750
16,0,3.0,Master. Eino Viljami Panula,male,1.0,4,1,39.6875
17,0,3.0,Master. Arthur Rice,male,4.0,4,1,29.1250
18,0,3.0,Master. Clarence Gustaf Hugo Asplund,male,9.0,4,2,31.3875
19,1,3.0,Miss. Lillian Gertrud Asplund,female,5.0,4,2,31.3875
20,1,3.0,Master. Edvin Rojj Felix Asplund,male,3.0,4,2,31.3875
21,0,3.0,Mr. Ernesti Arvid Panula,male,16.0,4,1,39.6875
22,0,3.0,Master. Eric Rice,male,7.0,4,1,29.1250
23,0,3.0,Miss. Ingeborg Constanzia Andersson,female,9.0,4,2,31.2750
24,0,3.0,Miss. Sigrid Elisabeth Andersson,female,11.0,4,2,31.2750
25,0,3.0,Mr. Jaako Arnold Panula,male,14.0,4,1,39.6875
26,0,3.0,Master. George Hugh Rice,male,8.0,4,1,29.1250
27,0,3.0,Miss. Ebba Iris Alfrida Andersson,female,6.0,4,2,31.2750
28,0,3.0,Master. Urho Abraham Panula,male,2.0,4,1,39.6875
29,0,3.0,Master. Sigvard Harald Elias Andersson,male,4.0,4,2,31.2750
...,...,...,...,...,...,...,...,...
857,0,2.0,Rev. John Harper,male,28.0,0,1,33.0000
858,0,3.0,Mr. Johan Svensson,male,74.0,0,0,7.7750
859,1,1.0,Miss. Mary Conover Lines,female,16.0,0,1,39.4000
860,1,3.0,Mrs. Sam (Leah Rosen) Aks,female,18.0,0,1,9.3500
861,1,1.0,Mr. Peter Denis Daly,male,51.0,0,0,26.5500
862,1,3.0,Mrs. Solomon (Latifa Qurban) Baclini,female,24.0,0,3,19.2583
863,0,3.0,Mr. Raihed Razi,male,30.0,0,0,7.2292
864,1,1.0,Mrs. Frederick Joel (Margaret Welles Barron) S...,female,48.0,0,0,25.9292
865,0,2.0,Mr. John William Gill,male,24.0,0,0,13.0000
866,1,2.0,Mrs. (Karolina) Bystrom,female,42.0,0,0,13.0000
867,0,1.0,Mr. Washington Augustus II Roebling,man,31.0,0,0,50.4958
868,0,3.0,Mr. Philemon van Melkebeke,male,23.0,0,0,9.5000
869,0,3.0,Mr. Cerin Balkic,male,26.0,0,0,7.8958
870,0,1.0,Mr. Frans Olof Carlsson,male,33.0,0,0,5.0000
871,0,3.0,Mr. Victor Vander Cruyssen,male,47.0,0,0,9.0000
872,1,3.0,Miss. Adele Kiamie Najib,female,15.0,0,0,7.2250
873,0,3.0,Mr. Alfred Ossian Gustafsson,male,20.0,0,0,9.8458
874,0,3.0,Mr. Nedelio Petroff,male,19.0,0,0,7.8958
875,0,3.0,Mr. Kristo Laleff,male,23.0,0,0,7.8958
876,1,1.0,Mrs. Thomas Jr (Lily Alexenia Wilson) Potter,female,56.0,0,1,83.1583
877,1,2.0,Mrs. William (Imanita Parrish Hall) Shelley,female,25.0,0,1,26.0000
878,0,3.0,Mr. Johann Markun,male,33.0,0,0,7.8958
879,0,3.0,Miss. Gerda Ulrika Dahlberg,female,22.0,0,0,10.5167
880,0,2.0,Mr. Frederick James Banfield,male,28.0,0,0,10.5000
881,0,3.0,Mr. Henry Jr Sutehall,male,25.0,0,0,7.0500
882,0,3.0,Mrs. William (Margaret Norton) Rice,female,39.0,0,5,29.1250
883,0,2.0,Rev. Juozas Montvila,male,27.0,0,0,13.0000
884,1,1.0,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
885,1,1.0,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3.0,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [4]:
pandas_profiling.ProfileReport(df)

/home/t-katou/.local/lib/python3.6/site-packages/matplotlib/font_manager.py:1241: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
  (prop.get_family(), self.defaultFamily[fontext]))
/home/t-katou/.local/lib/python3.6/site-packages/matplotlib/font_manager.py:1241: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
  (prop.get_family(), self.defaultFamily[fontext]))
/home/t-katou/.local/lib/python3.6/site-packages/matplotlib/font_manager.py:1241: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
  (prop.get_family(), self.defaultFamily[fontext]))
/home/t-katou/.local/lib/python3.6/site-packages/matplotlib/font_manager.py:1241: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
  (prop.get_family(), self.defaultFamily[fontext]))
/home/t-katou/.local/lib/python3.6/site-packages/matplotlib/font_manager.py:1241: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
  (prop.get_family(), self.defaultFamily[fontext]))
/home/t-katou/.local/lib/python3.6/site-packages/matplotlib/font_manager.py:1241: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
  (prop.get_family(), self.defaultFamily[fontext]))

In [5]:
print(df.Age.mean())
df.Age.sort_values(ascending=False)

113.62815107102593

404    74435.00
788      218.00
605      155.00
702       80.00
858       74.00
338       71.00
606       71.00
353       70.50
730       70.00
251       70.00
643       69.00
621       66.00
303       66.00
310       65.00
465       65.00
580       65.00
179       64.00
646       64.00
316       64.00
601       63.00
136       63.00
664       62.00
653       62.00
659       62.00
446       62.00
842       62.00
498       61.00
391       61.00
697       61.00
389       60.00
         ...
39         3.00
20         3.00
40         3.00
169        3.00
198        2.00
15         2.00
139        2.00
151        2.00
43         2.00
107        2.00
28         2.00
598        2.00
30         2.00
414        2.00
12         2.00
840        1.00
263        1.00
9          1.00
52         1.00
115        1.00
534        1.00
16         1.00
140        0.92
325        0.83
271        0.83
68         0.75
62         0.75
256        0.67
822        0.42
666      -22.00
Name: Age, Length: 887, dtype: float64

In [6]:
df[df.Age > 100]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
404,1,1.0,Mrs. James Joseph (Margaret Tobin) Brown,female,74435.0,0,0,27.7208
605,0,1.0,Mr. Harry Markland Molson,male,155.0,0,0,30.5000
788,0,2.0,Mr. Percy Andrew Bailey,male,218.0,0,0,11.5000

In [7]:
df.iloc[404]

Survived                                                          1
Pclass                                                            1
Name                       Mrs. James Joseph (Margaret Tobin) Brown
Sex                                                          female
Age                                                           74435
Siblings/Spouses Aboard                                           0
Parents/Children Aboard                                           0
Fare                                                        27.7208
Name: 404, dtype: object

In [10]:
df = df.drop(index=[404,605,788])

In [ ]:
save = df

In [11]:
df.iloc[404]

Survived                                     1
Pclass                                       1
Name                       Miss. Elise Lurette
Sex                                     female
Age                                         58
Siblings/Spouses Aboard                      0
Parents/Children Aboard                      0
Fare                                   146.521
Name: 405, dtype: object

In [12]:
df.Age.sort_values(ascending=True)

666   -22.00
822     0.42
256     0.67
62      0.75
68      0.75
325     0.83
271     0.83
140     0.92
16      1.00
9       1.00
263     1.00
115     1.00
52      1.00
840     1.00
534     1.00
28      2.00
43      2.00
30      2.00
139     2.00
15      2.00
198     2.00
414     2.00
107     2.00
598     2.00
12      2.00
151     2.00
88      3.00
169     3.00
120     3.00
40      3.00
       ...
389    60.00
212    60.00
746    60.00
236    60.00
391    61.00
697    61.00
498    61.00
446    62.00
664    62.00
842    62.00
659    62.00
653    62.00
136    63.00
601    63.00
316    64.00
646    64.00
179    64.00
580    65.00
310    65.00
465    65.00
621    66.00
303    66.00
643    69.00
251    70.00
730    70.00
353    70.50
338    71.00
606    71.00
858    74.00
702    80.00
Name: Age, Length: 884, dtype: float64

In [13]:
df = df.drop(index=[666])

In [14]:
df.Age.mean()

29.447531143827856

In [15]:
df[df.Pclass.isna()]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
36,0,NaN,Master. Henry Forbes Lefebre,male,5.0,3,1,25.4667
71,0,NaN,Mr. Lewis Hickman,male,32.0,2,0,73.5000
75,1,NaN,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
176,1,NaN,Mrs. Charles Alexander (Alice Adelaide Slow) L...,female,42.0,1,0,26.0000
280,1,NaN,Mrs. Richard Leonard (Sallie Monypeny) Beckwith,female,47.0,1,1,52.5542
370,0,NaN,Mr. Jeremiah Burke,NaN,19.0,0,0,6.7500
486,0,NaN,Mr. Howard Hugh Williams,male,28.0,0,0,8.0500
578,0,NaN,Mr. Joseph Peduzzi,male,24.0,0,0,8.0500

In [16]:
pivottablejs.pivot_ui(df)

In [ ]:
# df.iloc[36]=df.iloc[36].fillna({"Pclass":2})

In [22]:
for i in df[df.Pclass.isna()].index:
    i -= 1
    if df.iloc[i].Fare < 17:
        df.iloc[i] = df.iloc[i].fillna({"Pclass":3})
    elif df.iloc[i].Fare < 73:
        df.iloc[i] = df.iloc[i].fillna({"Pclass":2})
    else:
        df.iloc[i] = df.iloc[i].fillna({"Pclass":1})

In [33]:
df[df.Sex.isna()]

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, Siblings/Spouses Aboard, Parents/Children Aboard, Fare]
Index: []

In [34]:
df.Sex.unique()

array(['male', 'female'], dtype=object)

In [28]:
df.Sex = df.Sex.replace("man","male").replace("Woman", "female").replace("women","female")

In [32]:
df.iloc[108]=df.iloc[108].fillna({"Sex":"female"})
df.iloc[370]=df.iloc[370].fillna({"Sex":"male"})

In [36]:
df["Pclass"]= pd.get_dummies(df["Pclass"],drop_first=True)

In [38]:
df["Sex"] = df ["Sex"].map({"male":0, "female":1})
# 前処理終了

In [42]:
X = df.drop(columns = "Survived").drop(columns="Name")
Y = df["Survived"]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8)

In [44]:
random_forest=ensemble.RandomForestClassifier(max_depth=5)
random_forest.fit(X_train, Y_train)
random_forest.score(X_test,Y_test)

/home/t-katou/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

0.8700564971751412